' *********************************************************
' gfx_missile.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    6 ' frameboost
word    8, 3 ' width, height
' frame 0
word    $aa0a '   ██    
word    $755c ' █▓░░░░▓░
word    $aa0a '   ██    

