' *********************************************************
' bullet_6x6.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    12 ' frameboost
word    6, 6 ' width, height
' frame 0
word    $aa5a '   ░░    
word    $a9f2 '  █▓▓░   
word    $a1fc ' █▓▓▓░█  
word    $a3fc ' █▓▓▓▓█  
word    $abc2 '  ██▓▓   
word    $aa0a '   ██    

