' *********************************************************
' bullet_4x4.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    8 ' frameboost
word    4, 4 ' width, height
' frame 0
word    $aa96 '  ░░     
word    $aa7c ' █▓▓░    
word    $aa7c ' █▓▓░    
word    $aa82 '  ██     

