' *********************************************************
' gfx_laser_8x1.spin
' generated by img2dat v0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    2
word    8, 1
word    $1554 ' █░░░░░░█

