' *********************************************************
' gfx_bullet_8x8.spin
' generated by img2dat v0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16
word    8, 8
word    $a96a '    ░░   
word    $9772 '  █▓░▓░░ 
word    $9dc2 '  ██▓░▓░ 
word    $37f0 ' ██▓▓▓░▓█
word    $1fcc ' █▓█▓▓▓░█
word    $bf32 '  █▓█▓▓▓ 
word    $80c2 '  ██▓███ 
word    $a82a '    ██   

