' *********************************************************
' gfx_hp.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    6 ' frameboost
word    8, 3 ' width, height
' frame 0
word    $8088 ' █ █ ███ 
word    $8080 ' ███ ███ 
word    $a888 ' █ █ █   

