' *********************************************************
' gfx_arrow_d.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    6 ' frameboost
word    5, 3 ' width, height
' frame 0
word    $a800 ' █████   
word    $aa02 '  ███    
word    $aa8a '   █     

