' *********************************************************
' gfx_healthbar.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16 ' frameboost
word    8, 8 ' width, height
word    $aad7 ' ▓░░▓    
word    $aa7c ' █▓▓░    
word    $aa7c ' █▓▓░    
word    $aa7c ' █▓▓░    
word    $aa7c ' █▓▓░    
word    $aa7c ' █▓▓░    
word    $aa7c ' █▓▓░    
word    $aac0 ' ███▓    
