' *********************************************************
' gfx_bullet.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16 ' frameboost
word    8, 8 ' width, height
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a9ea '    ▓░   
word    $ab2a '    █▓   
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
