' *********************************************************
' gfx_laser.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16 ' frameboost
word    8, 8 ' width, height
' frame 0
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $d557 ' ▓░░░░░░▓
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

