' *********************************************************
' gfx_head.spin
' generated by img2dat v0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16
word    8, 8
word    $aaaa '         
word    $800a '   █████ 
word    $3f72 '  █▓░▓▓▓█
word    $04f2 '  █▓▓█░██
word    $04f2 '  █▓▓█░██
word    $3fc2 '  ██▓▓▓▓█
word    $000a '   ██████
word    $aaaa '         

