' *********************************************************
' gfx_font4x4_w.spin
' generated by img2dat 0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    8
word    8, 4
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         
word    $aaa6 '  ░      

word    $aa99 ' ░ ░     
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaa5 ' ░░      
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aaa6 '  ░      
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa96 '  ░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         
word    $aaaa '         

word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa95 ' ░░░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaa6 '  ░      
word    $aaa6 '  ░      

word    $aaaa '         
word    $aa95 ' ░░░     
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaa6 '  ░      
word    $aaaa '         

word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aaa9 ' ░       
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aaa6 '  ░      
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aaa6 '  ░      
word    $aa96 '  ░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa96 '  ░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa96 '  ░░     
word    $aa95 ' ░░░     
word    $aa9a '   ░     
word    $aaaa '         

word    $aa96 '  ░░     
word    $aaa6 '  ░      
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aaa9 ' ░       
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaaa '         
word    $aaa6 '  ░      
word    $aaa9 ' ░       

word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaaa '         
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa96 '  ░░     
word    $aaaa '         
word    $aaa6 '  ░      

word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaa9 ' ░       
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaa5 ' ░░      
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaa5 ' ░░      
word    $aaa9 ' ░       
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaa6 '  ░      
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa9a '   ░     
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaa9 ' ░       
word    $aaa9 ' ░       
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaa9 ' ░       
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aa96 '  ░░     
word    $aaa6 '  ░      
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aa99 ' ░ ░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aaa6 '  ░      
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aaa6 '  ░      
word    $aa96 '  ░░     
word    $aaaa '         

word    $aa96 '  ░░     
word    $aaa6 '  ░      
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaa9 ' ░       
word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aaa6 '  ░      
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa99 ' ░ ░     
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aa55 ' ░░░░    

word    $aa96 '  ░░     
word    $aaa5 ' ░░      
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaaa '         
word    $aa96 '  ░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa9 ' ░       
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaa9 ' ░       
word    $aaa6 '  ░      
word    $aaaa '         

word    $aa9a '   ░     
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaaa '         
word    $aa95 ' ░░░     
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaaa '         
word    $aa95 ' ░░░     
word    $aa96 '  ░░     
word    $aaa5 ' ░░      

word    $aaa9 ' ░       
word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaaa '         
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaaa '         
word    $aa9a '   ░     
word    $aa99 ' ░ ░     
word    $aaa6 '  ░      

word    $aaa9 ' ░       
word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $aa95 ' ░░░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaaa '         
word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa99 ' ░ ░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa99 ' ░ ░     
word    $aaa5 ' ░░      
word    $aaa9 ' ░       

word    $aaa6 '  ░      
word    $aa99 ' ░ ░     
word    $aa96 '  ░░     
word    $aa9a '   ░     

word    $aaa6 '  ░      
word    $aaa9 ' ░       
word    $aaa9 ' ░       
word    $aaaa '         

word    $aaaa '         
word    $aa96 '  ░░     
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa95 ' ░░░     
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $aa99 ' ░ ░     
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $aa99 ' ░ ░     
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaaa '         
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $aaaa '         
word    $aa95 ' ░░░     
word    $aa99 ' ░ ░     
word    $aaaa '         

word    $aaaa '         
word    $aa99 ' ░ ░     
word    $aa96 '  ░░     
word    $aaa5 ' ░░      

word    $aaaa '         
word    $aaa5 ' ░░      
word    $aa96 '  ░░     
word    $aaaa '         

word    $aa96 '  ░░     
word    $aaa5 ' ░░      
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaa5 ' ░░      
word    $aa96 '  ░░     
word    $aaa5 ' ░░      
word    $aaaa '         

word    $aa96 '  ░░     
word    $aaa5 ' ░░      
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

