' *********************************************************
' gfx_font6x8_normal.spin
' generated by img2dat 0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16
word    8, 8
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a110 ' ██░█░█  
word    $a554 ' █░░░░░  
word    $a110 ' ██░█░█  
word    $a110 ' ██░█░█  
word    $a554 ' █░░░░░  
word    $a110 ' ██░█░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a554 ' █░░░░░  
word    $a044 ' █░█░██  
word    $a554 ' █░░░░░  
word    $a440 ' ███░█░  
word    $a554 ' █░░░░░  
word    $a040 ' ███░██  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a414 ' █░░██░  
word    $a114 ' █░░█░█  
word    $a040 ' ███░██  
word    $a510 ' ██░█░░  
word    $a504 ' █░██░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a044 ' █░█░██  
word    $a010 ' ██░███  
word    $a444 ' █░█░█░  
word    $a104 ' █░██░█  
word    $a450 ' ██░░█░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a100 ' ████░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a004 ' █░████  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a004 ' █░████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a110 ' ██░█░█  
word    $a040 ' ███░██  
word    $a554 ' █░░░░░  
word    $a040 ' ███░██  
word    $a110 ' ██░█░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a554 ' █░░░░░  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a010 ' ██░███  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a050 ' ██░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a400 ' █████░  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a004 ' █░████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a504 ' █░██░░  
word    $a444 ' █░█░█░  
word    $a444 ' █░█░█░  
word    $a414 ' █░░██░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a044 ' █░█░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a400 ' █████░  
word    $a150 ' ██░░░█  
word    $a004 ' █░████  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a140 ' ███░░█  
word    $a400 ' █████░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a100 ' ████░█  
word    $a140 ' ███░░█  
word    $a110 ' ██░█░█  
word    $a104 ' █░██░█  
word    $a554 ' █░░░░░  
word    $a100 ' ████░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a004 ' █░████  
word    $a154 ' █░░░░█  
word    $a400 ' █████░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a004 ' █░████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a400 ' █████░  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a550 ' ██░░░░  
word    $a400 ' █████░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a010 ' ██░███  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a040 ' ███░██  
word    $a100 ' ████░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a550 ' ██░░░░  
word    $a000 ' ██████  
word    $a550 ' ██░░░░  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a040 ' ███░██  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a504 ' █░██░░  
word    $a444 ' █░█░█░  
word    $a544 ' █░█░░░  
word    $a004 ' █░████  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a554 ' █░░░░░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a054 ' █░░░██  
word    $a104 ' █░██░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a104 ' █░██░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a004 ' █░████  
word    $a154 ' █░░░░█  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a004 ' █░████  
word    $a154 ' █░░░░█  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a004 ' █░████  
word    $a504 ' █░██░░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a554 ' █░░░░░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a400 ' █████░  
word    $a400 ' █████░  
word    $a400 ' █████░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a104 ' █░██░█  
word    $a044 ' █░█░██  
word    $a014 ' █░░███  
word    $a044 ' █░█░██  
word    $a104 ' █░██░█  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a514 ' █░░█░░  
word    $a444 ' █░█░█░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a414 ' █░░██░  
word    $a444 ' █░█░█░  
word    $a504 ' █░██░░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a444 ' █░█░█░  
word    $a504 ' █░██░░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a104 ' █░██░█  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a004 ' █░████  
word    $a150 ' ██░░░█  
word    $a400 ' █████░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a110 ' ██░█░█  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a444 ' █░█░█░  
word    $a110 ' ██░█░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a110 ' ██░█░█  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a110 ' ██░█░█  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a110 ' ██░█░█  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a400 ' █████░  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a540 ' ███░░░  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a540 ' ███░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a004 ' █░████  
word    $a010 ' ██░███  
word    $a040 ' ███░██  
word    $a100 ' ████░█  
word    $a400 ' █████░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a054 ' █░░░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a150 ' ██░░░█  
word    $a444 ' █░█░█░  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a555 ' ░░░░░░  

word    $a000 ' ██████  
word    $a140 ' ███░░█  
word    $a410 ' ██░██░  
word    $a054 ' █░░░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a400 ' █████░  
word    $a550 ' ██░░░░  
word    $a404 ' █░███░  
word    $a550 ' ██░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a540 ' ███░░░  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a540 ' ███░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a400 ' █████░  
word    $a400 ' █████░  
word    $a550 ' ██░░░░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a550 ' ██░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a004 ' █░████  
word    $a550 ' ██░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a500 ' ████░░  
word    $a040 ' ███░██  
word    $a140 ' ███░░█  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a550 ' ██░░░░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a550 ' ██░░░░  
word    $a400 ' █████░  
word    $a150 ' ██░░░█  

word    $a000 ' ██████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a400 ' █████░  
word    $a000 ' ██████  
word    $a400 ' █████░  
word    $a400 ' █████░  
word    $a400 ' █████░  
word    $a410 ' ██░██░  
word    $a140 ' ███░░█  

word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a110 ' ██░█░█  
word    $a050 ' ██░░██  
word    $a050 ' ██░░██  
word    $a110 ' ██░█░█  
word    $a410 ' ██░██░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a500 ' ████░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a114 ' █░░█░█  
word    $a444 ' █░█░█░  
word    $a444 ' █░█░█░  
word    $a444 ' █░█░█░  
word    $a444 ' █░█░█░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a154 ' █░░░░█  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a154 ' █░░░░█  
word    $a004 ' █░████  
word    $a004 ' █░████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a550 ' ██░░░░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a550 ' ██░░░░  
word    $a400 ' █████░  
word    $a400 ' █████░  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a540 ' ███░░░  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a004 ' █░████  
word    $a150 ' ██░░░█  
word    $a400 ' █████░  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a150 ' ██░░░█  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a500 ' ████░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a110 ' ██░█░█  
word    $a110 ' ██░█░█  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a444 ' █░█░█░  
word    $a444 ' █░█░█░  
word    $a444 ' █░█░█░  
word    $a110 ' ██░█░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a110 ' ██░█░█  
word    $a040 ' ███░██  
word    $a110 ' ██░█░█  
word    $a404 ' █░███░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a404 ' █░███░  
word    $a550 ' ██░░░░  
word    $a400 ' █████░  
word    $a150 ' ██░░░█  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a554 ' █░░░░░  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a554 ' █░░░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a540 ' ███░░░  
word    $a040 ' ███░██  
word    $a014 ' █░░███  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a540 ' ███░░░  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a054 ' █░░░██  
word    $a040 ' ███░██  
word    $a500 ' ████░░  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a110 ' ██░█░█  
word    $a044 ' █░█░██  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a104 ' █░██░█  
word    $a451 ' ░█░░█░  
word    $a411 ' ░█░██░  
word    $a451 ' ░█░░█░  
word    $a104 ' █░██░█  
word    $a050 ' ██░░██  

