' *********************************************************
' gfx_font6x8_bold_w.spin
' generated by img2dat v0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    16
word    8, 8
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a596 '  ░░ ░░  
word    $a596 '  ░░ ░░  
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a556 '  ░░░░░  
word    $a55a '   ░░░░  
word    $a55a '   ░░░░  
word    $a556 '  ░░░░░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $a556 '  ░░░░░  
word    $a956 '  ░░░░   
word    $a556 '  ░░░░░  
word    $a56a '    ░░░  
word    $a556 '  ░░░░░  
word    $a96a '    ░░   

word    $aaaa '         
word    $aaaa '         
word    $a656 '  ░░░ ░  
word    $a556 '  ░░░░░  
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $a596 '  ░░ ░░  
word    $aaaa '         

word    $aaaa '         
word    $aa5a '   ░░    
word    $a956 '  ░░░░   
word    $aa5a '   ░░    
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $aaaa '         

word    $aaaa '         
word    $aa96 '  ░░     
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $a556 '  ░░░░░  
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a556 '  ░░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aa5a '   ░░    

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a556 '  ░░░░░  
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a6aa '      ░  
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a596 '  ░░ ░░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a656 '  ░░░ ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a95a '   ░░░   
word    $a956 '  ░░░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a6aa '      ░  
word    $a55a '   ░░░░  
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a56a '    ░░░  
word    $a6aa '      ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a5aa '     ░░  
word    $a56a '    ░░░  
word    $a55a '   ░░░░  
word    $a596 '  ░░ ░░  
word    $a556 '  ░░░░░  
word    $a5aa '     ░░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $a6aa '      ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a6aa '      ░  
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a96a '    ░░   
word    $aaaa '         
word    $aaaa '         
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a96a '    ░░   
word    $aaaa '         
word    $aaaa '         
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aa5a '   ░░    

word    $aaaa '         
word    $aaaa '         
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $aaaa '         
word    $a55a '   ░░░░  
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aa5a '   ░░    
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aaaa '         
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a596 '  ░░ ░░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a956 '  ░░░░   
word    $a596 '  ░░ ░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a596 '  ░░ ░░  
word    $a956 '  ░░░░   
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $aa96 '  ░░     
word    $a596 '  ░░ ░░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a6aa '      ░  
word    $a6aa '      ░  
word    $a6aa '      ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a596 '  ░░ ░░  
word    $a956 '  ░░░░   
word    $aa56 '  ░░░    
word    $a956 '  ░░░░   
word    $a596 '  ░░ ░░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a656 '  ░░░ ░  
word    $a556 '  ░░░░░  
word    $a596 '  ░░ ░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a596 '  ░░ ░░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a596 '  ░░ ░░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $aa96 '  ░░     
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a6aa '      ░  
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a56a '    ░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a56a '    ░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aa96 '  ░░     
word    $aa5a '   ░░    
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $a6aa '      ░  
word    $aaaa '         

word    $aaaa '         
word    $a956 '  ░░░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a956 '  ░░░░   
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $a556 '  ░░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a555 ' ░░░░░░  

word    $aaaa '         
word    $a56a '    ░░░  
word    $a65a '   ░░ ░  
word    $a956 '  ░░░░   
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a56a '    ░░░  
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $a56a '    ░░░  
word    $aaaa '         

word    $aaaa '         
word    $a6aa '      ░  
word    $a6aa '      ░  
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $a56a '    ░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a55a '   ░░░░  

word    $aaaa '         
word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $aaaa '         
word    $a95a '   ░░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a6aa '      ░  
word    $aaaa '         
word    $a6aa '      ░  
word    $a6aa '      ░  
word    $a6aa '      ░  
word    $a65a '   ░░ ░  
word    $a56a '    ░░░  

word    $aaaa '         
word    $aa5a '   ░░    
word    $a55a '   ░░░░  
word    $a95a '   ░░░   
word    $a95a '   ░░░   
word    $a55a '   ░░░░  
word    $a65a '   ░░ ░  
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $aa96 '  ░░     
word    $aa96 '  ░░     

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a6aa '      ░  

word    $aaaa '         
word    $aaaa '         
word    $a56a '    ░░░  
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aa5a '   ░░    
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a55a '   ░░░░  
word    $aa96 '  ░░     
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a556 '  ░░░░░  
word    $a55a '   ░░░░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a96a '    ░░   
word    $a55a '   ░░░░  
word    $a696 '  ░░  ░  
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a696 '  ░░  ░  
word    $a55a '   ░░░░  
word    $a6aa '      ░  
word    $a55a '   ░░░░  

word    $aaaa '         
word    $aaaa '         
word    $a556 '  ░░░░░  
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $aa5a '   ░░    
word    $a556 '  ░░░░░  
word    $aaaa '         

word    $aaaa '         
word    $a56a '    ░░░  
word    $a96a '    ░░   
word    $aa56 '  ░░░    
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a56a '    ░░░  
word    $aaaa '         

word    $aaaa '         
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a956 '  ░░░░   
word    $a96a '    ░░   
word    $a5aa '     ░░  
word    $a96a '    ░░   
word    $a96a '    ░░   
word    $a956 '  ░░░░   
word    $aaaa '         

word    $aaaa '         
word    $a55a '   ░░░░  
word    $a956 '  ░░░░   
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $a95a '   ░░░   
word    $a596 '  ░░ ░░  
word    $a555 ' ░░░░░░  
word    $a655 ' ░░░░ ░  
word    $a555 ' ░░░░░░  
word    $a596 '  ░░ ░░  
word    $a95a '   ░░░   

