' *********************************************************
' ibot.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    16 ' frameboost
word    8, 8 ' width, height
' frame 0
word    $ab29 ' ░  █▓   
word    $adcb ' ▓ █▓░▓  
word    $8303 ' ▓███▓██ 
word    $d554 ' █░░░░░░▓
word    $3d7c ' █▓▓░░▓▓█
word    $8002 '  ██████ 
word    $a30a '   ██▓█  
word    $a82a '    ██   

