' *********************************************************
' cursor.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    6 ' frameboost
word    8, 3 ' width, height
' frame 0
word    $5aa5 ' ░░    ░░
word    $6aa9 ' ░      ░
word    $5aa5 ' ░░    ░░

