' *********************************************************
' gfx_bullet.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    2 ' frameboost
word    2, 1 ' width, height
' frame 0
word    $aaa0 ' ██      

