' *********************************************************
' key_b.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    16 ' frameboost
word    4, 8 ' width, height
' frame 0
word    $aaff ' ▓▓▓▓    
word    $aac3 ' ▓██▓    
word    $aac3 ' ▓██▓    
word    $aac3 ' ▓██▓    
word    $aac3 ' ▓██▓    
word    $aac3 ' ▓██▓    
word    $aac3 ' ▓██▓    
word    $aaff ' ▓▓▓▓    

