' *********************************************************
' led.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    8 ' frameboost
word    8, 4 ' width, height
' frame 0
word    $0000 ' ████████
word    $03c0 ' ███▓▓███
word    $03c0 ' ███▓▓███
word    $0000 ' ████████
' frame 1
word    $03c0 ' ███▓▓███
word    $355c ' █▓░░░░▓█
word    $355c ' █▓░░░░▓█
word    $03c0 ' ███▓▓███

