' *********************************************************
' gfx_font6x6.spin
' generated by img2dat v0.0.0
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    12
word    8, 6
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a044 ' █░█░██  
word    $a155 ' ░░░░░█  
word    $a044 ' █░█░██  
word    $a155 ' ░░░░░█  
word    $a044 ' █░█░██  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a155 ' ░░░░░█  
word    $a015 ' ░░░███  
word    $a150 ' ██░░░█  
word    $a155 ' ░░░░░█  
word    $a010 ' ██░███  

word    $a105 ' ░░██░█  
word    $a045 ' ░░█░██  
word    $a010 ' ██░███  
word    $a144 ' █░█░░█  
word    $a141 ' ░██░░█  
word    $a000 ' ██████  

word    $a014 ' █░░███  
word    $a014 ' █░░███  
word    $a055 ' ░░░░██  
word    $a011 ' ░█░███  
word    $a145 ' ░░█░░█  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a111 ' ░█░█░█  
word    $a054 ' █░░░██  
word    $a111 ' ░█░█░█  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a004 ' █░████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a004 ' █░████  
word    $a001 ' ░█████  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a141 ' ░██░░█  
word    $a111 ' ░█░█░█  
word    $a105 ' ░░██░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a014 ' █░░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a100 ' ████░█  
word    $a054 ' █░░░██  
word    $a001 ' ░█████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a050 ' ██░░██  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a050 ' ██░░██  
word    $a044 ' █░█░██  
word    $a041 ' ░██░██  
word    $a155 ' ░░░░░█  
word    $a040 ' ███░██  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a001 ' ░█████  
word    $a055 ' ░░░░██  
word    $a100 ' ████░█  
word    $a055 ' ░░░░██  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a001 ' ░█████  
word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a100 ' ████░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a154 ' █░░░░█  
word    $a100 ' ████░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a004 ' █░████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a004 ' █░████  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a050 ' ██░░██  
word    $a000 ' ██████  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a151 ' ░█░░░█  
word    $a151 ' ░█░░░█  
word    $a001 ' ░█████  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a155 ' ░░░░░█  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a055 ' ░░░░██  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a001 ' ░█████  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a055 ' ░░░░██  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a001 ' ░█████  
word    $a055 ' ░░░░██  
word    $a001 ' ░█████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a001 ' ░█████  
word    $a055 ' ░░░░██  
word    $a001 ' ░█████  
word    $a001 ' ░█████  
word    $a000 ' ██████  

word    $a154 ' █░░░░█  
word    $a001 ' ░█████  
word    $a151 ' ░█░░░█  
word    $a101 ' ░███░█  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a155 ' ░░░░░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a100 ' ████░█  
word    $a100 ' ████░█  
word    $a100 ' ████░█  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a041 ' ░██░██  
word    $a011 ' ░█░███  
word    $a015 ' ░░░███  
word    $a041 ' ░██░██  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a001 ' ░█████  
word    $a001 ' ░█████  
word    $a001 ' ░█████  
word    $a001 ' ░█████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a145 ' ░░█░░█  
word    $a111 ' ░█░█░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a105 ' ░░██░█  
word    $a111 ' ░█░█░█  
word    $a141 ' ░██░░█  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a055 ' ░░░░██  
word    $a001 ' ░█████  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a101 ' ░███░█  
word    $a111 ' ░█░█░█  
word    $a141 ' ░██░░█  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a001 ' ░█████  
word    $a054 ' █░░░██  
word    $a100 ' ████░█  
word    $a055 ' ░░░░██  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a044 ' █░█░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a111 ' ░█░█░█  
word    $a145 ' ░░█░░█  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a044 ' █░█░██  
word    $a010 ' ██░███  
word    $a044 ' █░█░██  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a004 ' █░████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a001 ' ░█████  
word    $a004 ' █░████  
word    $a010 ' ██░███  
word    $a040 ' ███░██  
word    $a100 ' ████░█  
word    $a000 ' ██████  

word    $a054 ' █░░░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a040 ' ███░██  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a044 ' █░█░██  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

word    $a004 ' █░████  
word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a054 ' █░░░██  
word    $a100 ' ████░█  
word    $a154 ' █░░░░█  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a004 ' █░████  
word    $a054 ' █░░░██  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a050 ' ██░░██  
word    $a000 ' ██████  

word    $a100 ' ████░█  
word    $a150 ' ██░░░█  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a154 ' █░░░░█  
word    $a004 ' █░████  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a140 ' ███░░█  
word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a104 ' █░██░█  
word    $a150 ' ██░░░█  
word    $a100 ' ████░█  
word    $a054 ' █░░░██  

word    $a001 ' ░█████  
word    $a055 ' ░░░░██  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a014 ' █░░███  
word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a000 ' ██████  
word    $a014 ' █░░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a004 ' █░████  

word    $a001 ' ░█████  
word    $a041 ' ░██░██  
word    $a011 ' ░█░███  
word    $a045 ' ░░█░██  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a014 ' █░░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a055 ' ░░░░██  
word    $a111 ' ░█░█░█  
word    $a111 ' ░█░█░█  
word    $a111 ' ░█░█░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a054 ' █░░░██  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a050 ' ██░░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a054 ' █░░░██  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a054 ' █░░░██  
word    $a004 ' █░████  

word    $a000 ' ██████  
word    $a150 ' ██░░░█  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a150 ' ██░░░█  
word    $a100 ' ████░█  

word    $a000 ' ██████  
word    $a144 ' █░█░░█  
word    $a014 ' █░░███  
word    $a004 ' █░████  
word    $a004 ' █░████  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a050 ' ██░░██  
word    $a014 ' █░░███  
word    $a140 ' ███░░█  
word    $a054 ' █░░░██  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a054 ' █░░░██  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a140 ' ███░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a101 ' ░███░█  
word    $a101 ' ░███░█  
word    $a044 ' █░█░██  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a101 ' ░███░█  
word    $a111 ' ░█░█░█  
word    $a111 ' ░█░█░█  
word    $a044 ' █░█░██  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a101 ' ░███░█  
word    $a054 ' █░░░██  
word    $a044 ' █░█░██  
word    $a101 ' ░███░█  
word    $a000 ' ██████  

word    $a000 ' ██████  
word    $a104 ' █░██░█  
word    $a104 ' █░██░█  
word    $a150 ' ██░░░█  
word    $a100 ' ████░█  
word    $a054 ' █░░░██  

word    $a000 ' ██████  
word    $a154 ' █░░░░█  
word    $a040 ' ███░██  
word    $a010 ' ██░███  
word    $a154 ' █░░░░█  
word    $a000 ' ██████  

word    $a150 ' ██░░░█  
word    $a010 ' ██░███  
word    $a015 ' ░░░███  
word    $a010 ' ██░███  
word    $a150 ' ██░░░█  
word    $a000 ' ██████  

word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a010 ' ██░███  
word    $a000 ' ██████  

word    $a015 ' ░░░███  
word    $a010 ' ██░███  
word    $a150 ' ██░░░█  
word    $a010 ' ██░███  
word    $a015 ' ░░░███  
word    $a000 ' ██████  

word    $a110 ' ██░█░█  
word    $a044 ' █░█░██  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  
word    $a000 ' ██████  

word    $a155 ' ░░░░░█  
word    $a101 ' ░███░█  
word    $a115 ' ░░░█░█  
word    $a101 ' ░███░█  
word    $a155 ' ░░░░░█  
word    $a000 ' ██████  

