' *********************************************************
' gfx_font6x6_g.spin
' generated by img2dat v0.1.5
' *********************************************************
PUB Addr
    return @gfx_data

DAT

gfx_data

word    12
word    8, 6
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         
word    $aa9a '   ░     
word    $aaaa '         

word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aa66 '  ░ ░    
word    $a955 ' ░░░░░   
word    $aa66 '  ░ ░    
word    $a955 ' ░░░░░   
word    $aa66 '  ░ ░    
word    $aaaa '         

word    $aa9a '   ░     
word    $a955 ' ░░░░░   
word    $aa95 ' ░░░     
word    $a95a '   ░░░   
word    $a955 ' ░░░░░   
word    $aa9a '   ░     

word    $a9a5 ' ░░  ░   
word    $aa65 ' ░░ ░    
word    $aa9a '   ░     
word    $a966 '  ░ ░░   
word    $a969 ' ░  ░░   
word    $aaaa '         

word    $aa96 '  ░░     
word    $aa96 '  ░░     
word    $aa55 ' ░░░░    
word    $aa99 ' ░ ░     
word    $a965 ' ░░ ░░   
word    $aaaa '         

word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaaa '         

word    $aa9a '   ░     
word    $aa6a '    ░    
word    $aa6a '    ░    
word    $aa6a '    ░    
word    $aa9a '   ░     
word    $aaaa '         

word    $aa9a '   ░     
word    $a999 ' ░ ░ ░   
word    $aa56 '  ░░░    
word    $a999 ' ░ ░ ░   
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aaa6 '  ░      

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a955 ' ░░░░░   
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aaaa '         

word    $a9aa '     ░   
word    $aa6a '    ░    
word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aaa9 ' ░       
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a969 ' ░  ░░   
word    $a999 ' ░ ░ ░   
word    $a9a5 ' ░░  ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa9a '   ░     
word    $aa96 '  ░░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9aa '     ░   
word    $aa56 '  ░░░    
word    $aaa9 ' ░       
word    $a955 ' ░░░░░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $aa5a '   ░░    
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa5a '   ░░    
word    $aa66 '  ░ ░    
word    $aa69 ' ░  ░    
word    $a955 ' ░░░░░   
word    $aa6a '    ░    
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $aaa9 ' ░       
word    $aa55 ' ░░░░    
word    $a9aa '     ░   
word    $aa55 ' ░░░░    
word    $aaaa '         

word    $aa56 '  ░░░    
word    $aaa9 ' ░       
word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $a9aa '     ░   
word    $aa6a '    ░    
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $a956 '  ░░░░   
word    $a9aa '     ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aaaa '         
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aaaa '         
word    $aa9a '   ░     
word    $aaa6 '  ░      

word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $a955 ' ░░░░░   
word    $aaaa '         
word    $a955 ' ░░░░░   
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aa9a '   ░     
word    $aa6a '    ░    
word    $aa9a '   ░     
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $aa5a '   ░░    
word    $aaaa '         
word    $aa9a '   ░     
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a959 ' ░ ░░░   
word    $a959 ' ░ ░░░   
word    $aaa9 ' ░       
word    $a956 '  ░░░░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a955 ' ░░░░░   
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $aa55 ' ░░░░    
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $aaa9 ' ░       
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa55 ' ░░░░    
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $aaa9 ' ░       
word    $aa55 ' ░░░░    
word    $aaa9 ' ░       
word    $a955 ' ░░░░░   
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $aaa9 ' ░       
word    $aa55 ' ░░░░    
word    $aaa9 ' ░       
word    $aaa9 ' ░       
word    $aaaa '         

word    $a956 '  ░░░░   
word    $aaa9 ' ░       
word    $a959 ' ░ ░░░   
word    $a9a9 ' ░   ░   
word    $a956 '  ░░░░   
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a955 ' ░░░░░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aaaa '         

word    $a9aa '     ░   
word    $a9aa '     ░   
word    $a9aa '     ░   
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa69 ' ░  ░    
word    $aa99 ' ░ ░     
word    $aa95 ' ░░░     
word    $aa69 ' ░  ░    
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aaa9 ' ░       
word    $aaa9 ' ░       
word    $aaa9 ' ░       
word    $aaa9 ' ░       
word    $a955 ' ░░░░░   
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a965 ' ░░ ░░   
word    $a999 ' ░ ░ ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a9a5 ' ░░  ░   
word    $a999 ' ░ ░ ░   
word    $a969 ' ░  ░░   
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa55 ' ░░░░    
word    $aaa9 ' ░       
word    $aaaa '         

word    $aa56 '  ░░░    
word    $a9a9 ' ░   ░   
word    $a999 ' ░ ░ ░   
word    $a969 ' ░  ░░   
word    $a956 '  ░░░░   
word    $aaaa '         

word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $aaa9 ' ░       
word    $aa56 '  ░░░    
word    $a9aa '     ░   
word    $aa55 ' ░░░░    
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa66 '  ░ ░    
word    $aa9a '   ░     
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a999 ' ░ ░ ░   
word    $a965 ' ░░ ░░   
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $aa66 '  ░ ░    
word    $aa9a '   ░     
word    $aa66 '  ░ ░    
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $aa6a '    ░    
word    $aa9a '   ░     
word    $aaa6 '  ░      
word    $a955 ' ░░░░░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aaa9 ' ░       
word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aa6a '    ░    
word    $a9aa '     ░   
word    $aaaa '         

word    $aa56 '  ░░░    
word    $aa6a '    ░    
word    $aa6a '    ░    
word    $aa6a '    ░    
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa9a '   ░     
word    $aa66 '  ░ ░    
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $a955 ' ░░░░░   
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa9a '   ░     
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $aaaa '         
word    $aa56 '  ░░░    
word    $a9aa '     ░   
word    $a956 '  ░░░░   
word    $a956 '  ░░░░   
word    $aaaa '         

word    $aaa6 '  ░      
word    $aa56 '  ░░░    
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aaaa '         
word    $aa5a '   ░░    
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aa5a '   ░░    
word    $aaaa '         

word    $a9aa '     ░   
word    $a95a '   ░░░   
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $a95a '   ░░░   
word    $aaaa '         

word    $aaaa '         
word    $aa5a '   ░░    
word    $a956 '  ░░░░   
word    $aaa6 '  ░      
word    $a95a '   ░░░   
word    $aaaa '         

word    $a96a '    ░░   
word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $a95a '   ░░░   
word    $a9a6 '  ░  ░   
word    $a95a '   ░░░   
word    $a9aa '     ░   
word    $aa56 '  ░░░    

word    $aaa9 ' ░       
word    $aa55 ' ░░░░    
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aa9a '   ░     
word    $aaaa '         
word    $aa96 '  ░░     
word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa9a '   ░     
word    $aaaa '         
word    $aa96 '  ░░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaa6 '  ░      

word    $aaa9 ' ░       
word    $aa69 ' ░  ░    
word    $aa99 ' ░ ░     
word    $aa65 ' ░░ ░    
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aa96 '  ░░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aaaa '         
word    $aa55 ' ░░░░    
word    $a999 ' ░ ░ ░   
word    $a999 ' ░ ░ ░   
word    $a999 ' ░ ░ ░   
word    $aaaa '         

word    $aaaa '         
word    $aa56 '  ░░░    
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $aaaa '         

word    $aaaa '         
word    $aa5a '   ░░    
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $aa5a '   ░░    
word    $aaaa '         

word    $aaaa '         
word    $aa56 '  ░░░    
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $aa56 '  ░░░    
word    $aaa6 '  ░      

word    $aaaa '         
word    $a95a '   ░░░   
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $a95a '   ░░░   
word    $a9aa '     ░   

word    $aaaa '         
word    $a966 '  ░ ░░   
word    $aa96 '  ░░     
word    $aaa6 '  ░      
word    $aaa6 '  ░      
word    $aaaa '         

word    $aaaa '         
word    $aa5a '   ░░    
word    $aa96 '  ░░     
word    $a96a '    ░░   
word    $aa56 '  ░░░    
word    $aaaa '         

word    $aa9a '   ░     
word    $aa56 '  ░░░    
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $a96a '    ░░   
word    $aaaa '         

word    $aaaa '         
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $a95a '   ░░░   
word    $aaaa '         

word    $aaaa '         
word    $a9a9 ' ░   ░   
word    $a9a9 ' ░   ░   
word    $aa66 '  ░ ░    
word    $aa9a '   ░     
word    $aaaa '         

word    $aaaa '         
word    $a9a9 ' ░   ░   
word    $a999 ' ░ ░ ░   
word    $a999 ' ░ ░ ░   
word    $aa66 '  ░ ░    
word    $aaaa '         

word    $aaaa '         
word    $a9a9 ' ░   ░   
word    $aa56 '  ░░░    
word    $aa66 '  ░ ░    
word    $a9a9 ' ░   ░   
word    $aaaa '         

word    $aaaa '         
word    $a9a6 '  ░  ░   
word    $a9a6 '  ░  ░   
word    $a95a '   ░░░   
word    $a9aa '     ░   
word    $aa56 '  ░░░    

word    $aaaa '         
word    $a956 '  ░░░░   
word    $aa6a '    ░    
word    $aa9a '   ░     
word    $a956 '  ░░░░   
word    $aaaa '         

word    $a95a '   ░░░   
word    $aa9a '   ░     
word    $aa95 ' ░░░     
word    $aa9a '   ░     
word    $a95a '   ░░░   
word    $aaaa '         

word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aa9a '   ░     
word    $aaaa '         

word    $aa95 ' ░░░     
word    $aa9a '   ░     
word    $a95a '   ░░░   
word    $aa9a '   ░     
word    $aa95 ' ░░░     
word    $aaaa '         

word    $a99a '   ░ ░   
word    $aa66 '  ░ ░    
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         
word    $aaaa '         

word    $a955 ' ░░░░░   
word    $a9a9 ' ░   ░   
word    $a995 ' ░░░ ░   
word    $a9a9 ' ░   ░   
word    $a955 ' ░░░░░   
word    $aaaa '         

