#!/usr/bin/env python

import os, sys

from PIL import Image
import argparse


LS_SCREEN_W = 128
LS_SCREEN_H = 64

SCALEFACTOR = 4

PAGES = 8
ADDRESSES = 128
PIXELS_PER_ADDRESS = 8

def multiply_tuple(scalar,tup):
    return tuple([scalar*x for x in tup])


parser = argparse.ArgumentParser(description='Convert images to Propeller Spin data blocks for use with Lame Graphics.')

parser.add_argument('-m','--mode', nargs=1, metavar=('MODE'), choices=['sprite','font'], default=['sprite'],
        help="""Indicates what the image is to be converted into:
            sprite - An image with custom width/height and that may have multiple frames
            font - A bitmap font to be used with lame_text
        """)
parser.add_argument('-b','--bits', nargs=1, metavar=('BITS'), type=int, choices=[2,8],default=2,
        help="Bit depth of images.")

parser.add_argument('-f','--framesize', nargs=2, metavar=('WIDTH','HEIGHT'), type=int,
        help="Size of individual sprite frames (only needed for sprites).")

parser.add_argument('-d','--display', action='store_true',
        help="Show graphic comparison of old and new images.")

parser.add_argument('-o','--output', action='store_true',
        help="Print data output to screen.")

parser.add_argument('filenames', metavar='FILE', nargs='+', help='Files to convert')


args = parser.parse_args()

filenames = [ i for i in args.filenames if not os.path.splitext(i)[1] == '.dat' and os.path.isfile(i) ]
filenames = [ i for i in filenames if not os.path.splitext(i)[1] == '.txt' ]

if not filenames:
    print "No valid files selected"
else:
    for filename in filenames:
        newfilename = filename+".dat"

        im = Image.open(filename)
        im = im.convert("RGB")
        output_im = Image.new("RGB",im.size)
        output_txt = open(newfilename,'w')

        output_txt.write("gfx_%s\n" % os.path.splitext(os.path.basename(filename))[0])
        
        if args.mode[0] == 'sprite':

            # Check if framesize passed in arguments
            if args.framesize:
                framesize = tuple(args.framesize)
                if not framesize < im.size:
                    print "Frame is larger than image; exiting"
                    sys.exit(1)
            else:
                framesize = im.size

            
            # Calculate frameboost constant, the precalculated frame size so 
            # that jumping to a frame requires only one multiplication, not three.
            frameboost = (framesize[0]*2*framesize[1]/PIXELS_PER_ADDRESS) & 0xFFFF
            dimensions = ((framesize[0]/PIXELS_PER_ADDRESS) & 0xFFFF , (framesize[1]/PIXELS_PER_ADDRESS) & 0xFFFF) 

            output_txt.write("word\t$%X" % frameboost + "  'frameboost\n")
            output_txt.write("word\t$%X, $%X   'width, height\n" % dimensions )


        bytecount = 0

        for page in range(0,im.size[1]/PIXELS_PER_ADDRESS):
            for address in range(0,im.size[0]):

                colorchar = 0

                for pixel in range(0,PIXELS_PER_ADDRESS):

                    x = address
                    y = page*PIXELS_PER_ADDRESS + pixel

                    pixeldata = im.getpixel((x,y))

                    if type(pixeldata) is tuple:
                        coloravg = sum(pixeldata)/3
                    else:
                        coloravg = pixeldata


                    # if color is not black
                    if coloravg > 40:

                        if coloravg < 210:
                            colorchar += (1 << (pixel+8))

                            # Pink is the alpha color
                            if pixeldata == (255,0,255):
                                output_im.putpixel((x,y), (255, 0, 255))
                            else:
                                output_im.putpixel((x,y), (139, 138, 116))
                                colorchar += (1 << pixel)

                        else:
                            output_im.putpixel((x,y), (255, 233, 166))
                            colorchar += (1 << pixel)

                    else:
                        ## if black
                        output_im.putpixel((x,y), (23,43,66))


                if bytecount % 16 == 0:
                    output_txt.write("byte\t")
                output_txt.write("$%X" % (colorchar & 0xFF))
                output_txt.write(", ")
                output_txt.write("$%X" % (colorchar >> 8))
                if not bytecount % 16 == 15:
                    output_txt.write(", ")
                else:
                    output_txt.write("\n")

                bytecount += 1


        if args.display:
            # Create a canvas to paste both the input and output images onto
            output_canvas = Image.new("RGB",(im.size[0],im.size[1]*2))
            output_canvas.paste(im,(0,0))
            output_canvas.paste(output_im,(0,im.size[1]))

            # Then resize the canvas to make it easier to see
            output_canvas = output_canvas.resize(multiply_tuple(SCALEFACTOR,(im.size[0],im.size[1]*2)))
            output_canvas.show()


            output_txt.close()


        if args.output:
            print "   Creating:",newfilename
            print "  Bit depth:", args.bits
            print " Image Type:", args.mode[0]
            print " Image size:",im.size
            print " Frame size:",framesize

            print open(newfilename,'r').read()
