' *********************************************************
' bullet_8x8.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    16 ' frameboost
word    8, 8 ' width, height
' frame 0
word    $a96a '    ░░   
word    $9772 '  █▓░▓░░ 
word    $9dc2 '  ██▓░▓░ 
word    $37f0 ' ██▓▓▓░▓█
word    $1fcc ' █▓█▓▓▓░█
word    $bf32 '  █▓█▓▓▓ 
word    $80c2 '  ██▓███ 
word    $a82a '    ██   

