' *********************************************************
' two_bullets.spin
' Graphics generated by img2dat
' *********************************************************
PUB Addr
    return @data

DAT

data

word    18 ' frameboost
word    8, 9 ' width, height
' frame 0
word    $0150 ' ██░░░███
word    $07f4 ' █░▓▓▓░██
word    $dd5d ' ░▓░░░▓░▓
word    $d3f1 ' ░█▓▓▓█░▓
word    $d001 ' ░█████░▓
word    $d3f1 ' ░█▓▓▓█░▓
word    $dd5d ' ░▓░░░▓░▓
word    $07f4 ' █░▓▓▓░██
word    $0150 ' ██░░░███

